# Generated by Django 3.1.7 on 2021-04-05 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now, validators=[shop.models.Item.validate_date])),
                ('order_date', models.DateField(default=django.utils.timezone.now, validators=[shop.models.Item.validate_date])),
                ('quantity', models.IntegerField(default=0, validators=[shop.models.Item.validate_quantity])),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=500)),
                ('purchasePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[shop.models.Medicine.validate_price])),
                ('unit_selling', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[shop.models.Medicine.validate_price])),
                ('threshold_value', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=0, validators=[shop.models.Transaction.validate_quantity])),
                ('date', models.DateField(default=django.utils.timezone.now, validators=[shop.models.Transaction.validate_date])),
                ('expiry_date', models.DateField(default=django.utils.timezone.now, validators=[shop.models.Transaction.validate_date])),
                ('batch_id', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone Number is not valid', regex='^(?:\\s+|)((0|(?:(\\+|)91))(?:\\s|-)*(?:(?:\\d(?:\\s|-)*\\d{9})|(?:\\d{2}(?:\\s|-)*\\d{8})|(?:\\d{3}(?:\\s|-)*\\d{7}))|\\d{10})(?:\\s+|)')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.transaction')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone Number is not valid', regex='^(?:\\s+|)((0|(?:(\\+|)91))(?:\\s|-)*(?:(?:\\d(?:\\s|-)*\\d{9})|(?:\\d{2}(?:\\s|-)*\\d{8})|(?:\\d{3}(?:\\s|-)*\\d{7}))|\\d{10})(?:\\s+|)')])),
            ],
            bases=('shop.transaction',),
        ),
        migrations.CreateModel(
            name='ExpiredItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
            ],
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='UsableItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
            ],
            bases=('shop.item',),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.vendor'),
        ),
        migrations.AddField(
            model_name='item',
            name='medicine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.medicine'),
        ),
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.transaction')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
            bases=('shop.transaction',),
        ),
    ]
